---
title: "Gargantua"
subtitle: "HomeLab"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "5"
theme: default
colors:
  light:
    highlight-primary: "#f1f1f1"
    highlight-secondary: "#f1f1f1"
    highlight-hover: "#1B0273"
    background: "#F2A7A7"
    card-background: "#f1f1f1"
    text: "#ffffff"
    text-header: "#1B0273"
    text-title: "#1B0273"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#fafafa"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper-light.jpg"
  dark:
    highlight-primary: "#1B0273"
    highlight-secondary: "#1B0273"
    highlight-hover: "#8C035C"
    background: "#8C035C"
    card-background: "#1B0273"
    text: "#f9f9f9"
    text-header: "#D90452"
    text-title: "#f5f5f5"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#f9f9f9"
    link-hover: "#f5f5f5"
    background-image: "../assets/wallpaper-dark.jpg"

services:
  - name: "Multimedia"
    icon: "fas fa-film"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.ico"
        subtitle: "Movie & TV Shows streaming"
        tag: "streaming"
        tagstyle: "is-multimidea"
        url: "http://jellyfin.sv"
        target: "_blank"
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Content streaming"
        tag: "streaming"
        tagstyle: "is-multimidea"
        url: "http://plex.sv"
        target: "_blank"
      - name: "Overseerr"
        logo: "assets/tools/overseerr.png"
        subtitle: "Content request handler"
        tag: "torrent"
        tagstyle: "is-multimidea"
        url: "http://overseerr.sv"
        target: "_blank"
      - name: "OpenBooks"
        logo: "assets/tools/openbooks.png"
        subtitle: "Open library"
        tag: "books"
        tagstyle: "is-multimidea"
        url: "http://overseerr.sv"
        target: "_blank"
  - name: "Services"
    icon: "fas fa-server"
    items:
      - name: "Code Server"
        logo: "assets/tools/vscode.ico"
        subtitle: "Development tool"
        tag: "development"
        tagstyle: "is-services"
        url: "http://code.sv"
        target: "_blank"
      - name: "Pihole"
        logo: "assets/tools/pihole.ico"
        subtitle: "Network Adblocker"
        tag: "ad-blocker"
        tagstyle: "is-services"
        url: "http://pihole.sv/admin"
        target: "_blank"
      - name: "Webtop"
        logo: "assets/tools/webtop.png"
        subtitle: "Web full desktop environments"
        tag: "container"
        tagstyle: "is-services"
        url: "http://webtop.sv"
        target: "_blank"
      - name: "YouTube DL"
        logo: "assets/tools/youtube.ico"
        subtitle: "YouTube video downloader"
        tag: "downloader"
        tagstyle: "is-services"
        url: "http://ytdownload.sv"
        target: "_blank"
  - name: "Management"
    icon: "fas fa-network-wired"
    items:
      - name: "Webmin"
        logo: "assets/tools/webmin.png"
        subtitle: "Server management"
        tag: "server"
        tagstyle: "is-management"
        url: "http://webmin.sv"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/portainer.ico"
        subtitle: "Container management"
        tag: "docker"
        tagstyle: "is-management"
        url: "http://portainer.sv"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginx.png"
        subtitle: "Proxy manager"
        tag: "network"
        tagstyle: "is-management"
        url: "http://npm.sv"
        target: "_blank"
      - name: "Router dashboard"
        logo: "assets/tools/router.ico"
        subtitle: "Network admin panel"
        tag: "network"
        tagstyle: "is-management"
        url: "http://router.sv"
        target: "_blank"
  - name: "Torrent"
    icon: "fas fa-download"
    items:
      - name: "Flood"
        logo: "assets/tools/flood.ico"
        subtitle: "Transmission interface"
        tag: "torrent"
        tagstyle: "is-torrent"
        url: "http://flood.sv"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/radarr.ico"
        subtitle: "Movie downloader"
        tag: "torrent"
        tagstyle: "is-torrent"
        url: "http://radarr.sv"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.ico"
        subtitle: "TV shows downloader"
        tag: "torrent"
        tagstyle: "is-torrent"
        url: "http://sonarr.sv"
        target: "_blank"
      - name: "Lidarr"
        logo: "assets/tools/lidarr.ico"
        subtitle: "Music downloader"
        tag: "torrent"
        tagstyle: "is-torrent"
        url: "http://lidarr.sv"
        target: "_blank"
      - name: "Readarr"
        logo: "assets/tools/readarr.ico"
        subtitle: "Books downloader"
        tag: "torrent"
        tagstyle: "is-torrent"
        url: "http://readarr.sv"
        target: "_blank"
      - name: "Bazarr"
        logo: "assets/tools/bazarr.png"
        subtitle: "Subtitle companion for Radarr and Sonarr"
        tag: "torrent"
        tagstyle: "is-torrent"
        url: "http://bazarr.sv"
        target: "_blank"
      - name: "Jackett"
        logo: "assets/tools/jackett.ico"
        subtitle: "Torrent indexer"
        tag: "torrent"
        tagstyle: "is-torrent"
        url: "http://jackett.sv"
        target: "_blank"
  - name: "Monitoring"
    icon: "fas fa-search"
    items:
      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.png"
        subtitle: "Uptime services dashboard"
        tag: "network"
        tagstyle: "is-monitoring"
        url: "http://kuma.sv"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Analytics & monitoring dashboard"
        tag: "network"
        tagstyle: "is-monitoring"
        url: "http://grafana.sv"
        target: "_blank"
      - name: "Prometheus"
        logo: "assets/tools/prometheus.ico"
        subtitle: "Monitoring system"
        tag: "network"
        tagstyle: "is-monitoring"
        url: "http://prometheus.sv"
        target: "_blank"