---
title: "Gargantua"
subtitle: "HomeLab"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3"
theme: default
colors:
  light:
    highlight-primary: "#f1f1f1"
    highlight-secondary: "#f1f1f1"
    highlight-hover: "#1B0273"
    background: "#F2A7A7"
    card-background: "#f1f1f1"
    text: "#ffffff"
    text-header: "#1B0273"
    text-title: "#1B0273"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#fafafa"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper-light.jpg"
  dark:
    highlight-primary: "#1B0273"
    highlight-secondary: "#1B0273"
    highlight-hover: "#8C035C"
    background: "#8C035C"
    card-background: "#1B0273"
    text: "#f9f9f9"
    text-header: "#D90452"
    text-title: "#f5f5f5"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#f9f9f9"
    link-hover: "#f5f5f5"
    background-image: "../assets/wallpaper-dark.jpg"

services:
  - name: "//Multimedia"
    icon: "fas fa-film"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Content streaming"
        tag: "streaming"
        tagstyle: "is-link"
        url: "http://plex.sv"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/radarr.ico"
        subtitle: "Movie downloader"
        tag: "torrent"
        tagstyle: "is-link"
        url: "http://radarr.sv"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.ico"
        subtitle: "TV shows downloader"
        tag: "torrent"
        tagstyle: "is-link"
        url: "http://sonarr.sv"
        target: "_blank"
      - name: "Lidarr"
        logo: "assets/tools/lidarr.ico"
        subtitle: "Music downloader"
        tag: "torrent"
        tagstyle: "is-link"
        url: "http://lidarr.sv"
        target: "_blank"
      - name: "Readarr"
        logo: "assets/tools/readarr.ico"
        subtitle: "Books downloader"
        tag: "torrent"
        tagstyle: "is-link"
        url: "http://readarr.sv"
        target: "_blank"
  - name: "//Services"
    icon: "fas fa-server"
    items:
      - name: "Pihole"
        logo: "assets/tools/pihole.ico"
        subtitle: "Network Adblocker"
        tag: "ad-blocker"
        tagstyle: "is-warning"
        url: "http://pihole.sv/admin"
        target: "_blank"
      - name: "Flood"
        logo: "assets/tools/flood.ico"
        subtitle: "Transmission interface"
        tag: "torrent"
        tagstyle: "is-warning"
        url: "http://flood.sv"
        target: "_blank"
      - name: "Jackett"
        logo: "assets/tools/jackett.ico"
        subtitle: "Torrent indexer"
        tag: "torrent"
        tagstyle: "is-warning"
        url: "http://jackett.sv"
        target: "_blank"
  - name: "//Management"
    icon: "fas fa-network-wired"
    items:
      - name: "Webmin"
        logo: "assets/tools/webmin.png"
        subtitle: "Server management"
        tag: "server"
        tagstyle: "is-danger"
        url: "http://webmin.sv"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/portainer.ico"
        subtitle: "Container management"
        tag: "docker"
        tagstyle: "is-danger"
        url: "http://portainer.sv"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginx.png"
        subtitle: "Proxy manager"
        tag: "network"
        tagstyle: "is-danger"
        url: "http://npm.sv"
        target: "_blank"
      - name: "Router dashboard"
        logo: "assets/tools/router.ico"
        subtitle: "Network admin panel"
        tag: "network"
        tagstyle: "is-danger"
        url: "http://router.sv"
        target: "_blank"